FROM jmaggio14/imagepypelines:base

# OPENCV RECOMPILE WITH GPU SUPPORT
ENV IP_GPU_ENABLED=1
WORKDIR /
RUN wget -N https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip \
&& unzip -o ${OPENCV_VERSION}.zip \
&& rm ${OPENCV_VERSION}.zip
RUN wget -N https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip \
&& unzip -o ${OPENCV_VERSION}.zip \
&& mkdir /opencv-${OPENCV_VERSION}/cmake_binary \
&& cd /opencv-${OPENCV_VERSION}/cmake_binary \
&& cmake -DBUILD_TIFF=ON \
  -DBUILD_opencv_java=OFF \
  -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib-${OPENCV_VERSION}/modules \
  -DWITH_CUDA=$IP_GPU_ENABLED \
  -DWITH_OPENGL=ON \
  -DWITH_GSTREAMER=ON \
  -DWITH_GSTREAMER_0_10=OFF \
  -DENABLE_FAST_MATH=1 \
  -DCUDA_FAST_MATH==$IP_GPU_ENABLED \
  -DWITH_CUBLAS==$IP_GPU_ENABLED \
  -DWITH_OPENCL=OFF \
  -DWITH_IPP=ON \
  -DWITH_TBB=ON \
  -DWITH_EIGEN=ON \
  -DWITH_V4L=ON \
  -DBUILD_TESTS=OFF \
  -DBUILD_PERF_TESTS=OFF \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DCMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") \
  -DPYTHON_EXECUTABLE=$(which python3) \
  -DPYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
  -DPYTHON_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \
  .. \
&& make install \
&& rm /${OPENCV_VERSION}.zip \
&& rm -rf /opencv-${OPENCV_VERSION} \
&& rm -rf /opencv_contrib-${OPENCV_VERSION}

# UNINSTALL TENSORFLOW AND REINSTALL WITH GPU SUPPORT
RUN pip uninstall tensorflow==1.12.0
RUN pip install tensorflow-gpu==1.12.0
